<?php

return array(
	'version' => '0.9.4',
	'pgcache.enabled' => true,
	'pgcache.engine' => 'file',
	'minify.enabled' => true,
	'minify.auto' => false,
	'minify.engine' => 'file',
	'minify.html.engine' => 'html',
	'minify.js.engine' => 'js',
	'minify.css.engine' => 'css',
	'dbcache.enabled' => false,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => false,
	'objectcache.engine' => 'file',
	'browsercache.enabled' => true,
	'cdn.enabled' => false,
	'cdn.engine' => 'ftp',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'newrelic.enabled' => false,
	'newrelic.api_key' => '',
	'newrelic.account_id' => '',
	'newrelic.appname' => '',
	'newrelic.application_id' => 0,
	'plugin.license_key' => '',
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'common.instance_id' => 1914478270,
	'plugin.type' => '',
	'common.support' => '',
	'common.tweeted' => false,
	'notes.support_us' => false,
	'minify.rewrite' => true,
	'minify.reject.logged' => false,
	'minify.html.enable' => true,
	'minify.html.inline.css' => true,
	'minify.html.inline.js' => true,
	'minify.html.reject.feed' => false,
	'minify.html.strip.crlf' => true,
	'minify.html.comments.ignore' => array(
		0 => 'google_ad_',
		1 => 'RSPEAK_',
	),
	'minify.js.enable' => true,
	'minify.js.combine.header' => false,
	'minify.js.header.embed_type' => 'blocking',
	'minify.js.combine.body' => false,
	'minify.js.body.embed_type' => 'blocking',
	'minify.js.combine.footer' => false,
	'minify.js.footer.embed_type' => 'blocking',
	'minify.js.strip.comments' => false,
	'minify.js.strip.crlf' => false,
	'minify.css.enable' => true,
	'minify.css.combine' => false,
	'minify.css.strip.comments' => false,
	'minify.css.strip.crlf' => false,
	'minify.css.imports' => '',
	'minify.lifetime' => 86400,
	'minify.file.gc' => 86400,
	'minify.reject.uri' => array(
		0 => '',
	),
	'minify.reject.files.js' => array(
		0 => '',
	),
	'minify.reject.files.css' => array(
		0 => '',
	),
	'minify.reject.ua' => array(
		0 => 'MySiteApp',
	),
	'minify.js.groups' => array(
		'80d3c' => array(
			'archive' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						2 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						3 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						4 => 'wp-content/themes/cafemocha/js/navigation.js',
						5 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'author' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						4 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						5 => 'wp-content/themes/cafemocha/js/navigation.js',
						6 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'category' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'image' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/plugins/jetpack/modules/related-posts/related-posts.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
					),
				),
			),
			'forget' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'home-page' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'my-message' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/themes/cafemocha/autosuggest/src/jquery.tokeninput.js',
						5 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						6 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						7 => 'wp-content/themes/cafemocha/js/navigation.js',
						8 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'publish-document' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'registration' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/upload/upload.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'page' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'search' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						4 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						5 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						6 => 'wp-content/themes/cafemocha/js/navigation.js',
						7 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
					),
				),
			),
			'single' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/jetpack/_inc/postmessage.js',
						1 => 'wp-content/plugins/jetpack/_inc/jquery.inview.js',
						2 => 'wp-content/plugins/jetpack/_inc/jquery.jetpack-resize.js',
						3 => 'wp-content/plugins/jetpack/modules/related-posts/related-posts.js',
						4 => 'wp-content/themes/cafemocha/js/cafemocha/sip.js',
						5 => 'wp-content/plugins/jetpack/modules/photon/photon.js',
						6 => 'wp-content/plugins/jetpack/modules/wpgroho.js',
						7 => 'wp-content/themes/cafemocha/js/navigation.js',
						8 => 'wp-content/plugins/wp-social-invitations/assets/js/wsi.js',
						9 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.js',
					),
				),
			),
		),
	),
	'minify.css.groups' => array(
		'80d3c' => array(
			404 => array(
				'include' => array(
					'files' => array(
						0 => 'cdn-cgi/se/themes/core.css',
						1 => 'cdn-cgi/se/themes/mountain-view/styles.css',
					),
				),
			),
			'archive' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'author' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'category' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'image' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/related-posts/related-posts.css',
						5 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'forget' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
						9 => 'wp-content/themes/cafemocha/js/bxslider/jquery.bxslider.css',
					),
				),
			),
			'home-page' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
						9 => 'wp-content/themes/cafemocha/js/bxslider/jquery.bxslider.css',
					),
				),
			),
			'my-message' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
						9 => 'wp-content/themes/cafemocha/autosuggest/styles/token-input.css',
						10 => 'wp-content/themes/cafemocha/autosuggest/styles/token-input-facebook.css',
					),
				),
			),
			'publish-document' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
						9 => 'wp-content/themes/cafemocha/js/bxslider/jquery.bxslider.css',
					),
				),
			),
			'registration' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'page' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
						9 => 'wp-content/themes/cafemocha/js/bxslider/jquery.bxslider.css',
					),
				),
			),
			'search' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						5 => 'http://fonts.googleapis.com/css',
						6 => 'wp-content/themes/cafemocha/style.css',
						7 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						8 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
			'single' => array(
				'include' => array(
					'files' => array(
						0 => 'wp-content/plugins/wp-social-invitations/assets/css/style.css',
						1 => 'wp-content/plugins/wpcafemochaplg/css/style.css',
						2 => 'wp-content/plugins/jetpack/modules/likes/style.css',
						3 => 'wp-content/plugins/jetpack/modules/subscriptions/subscriptions.css',
						4 => 'wp-content/plugins/jetpack/modules/related-posts/related-posts.css',
						5 => 'wp-content/plugins/jetpack/modules/widgets/widgets.css',
						6 => 'http://fonts.googleapis.com/css',
						7 => 'wp-content/themes/cafemocha/style.css',
						8 => 'wp-content/plugins/jetpack/modules/sharedaddy/sharing.css',
						9 => 'http://cafemocha.org/?custom-css=1&csblog=1&cscache=6&csrev=3',
					),
				),
			),
		),
	),
	'notes.need_empty_minify' => false,
	'minify.debug' => false,
	'pgcache.debug' => false,
	'notes.need_empty_pgcache' => false,
	'notes.plugins_updated' => false,
	'browsercache.replace.exceptions' => array(
		0 => '',
	),
	'browsercache.no404wp' => false,
	'browsercache.no404wp.exceptions' => array(
		0 => 'robots\\.txt',
		1 => '[a-z0-9_\\-]*sitemap[a-z0-9_\\-]*\\.(xml|xsl|html)(\\.gz)?',
	),
	'browsercache.cssjs.last_modified' => true,
	'browsercache.cssjs.expires' => true,
	'browsercache.cssjs.lifetime' => 31536000,
	'browsercache.cssjs.cache.control' => true,
	'browsercache.cssjs.cache.policy' => 'cache_public_maxage',
	'browsercache.cssjs.etag' => true,
	'browsercache.cssjs.w3tc' => false,
	'browsercache.cssjs.compression' => true,
	'browsercache.cssjs.replace' => false,
	'browsercache.cssjs.nocookies' => true,
	'browsercache.html.last_modified' => true,
	'browsercache.html.expires' => true,
	'browsercache.html.lifetime' => 3600,
	'browsercache.html.cache.control' => true,
	'browsercache.html.cache.policy' => 'cache_public_maxage',
	'browsercache.html.etag' => true,
	'browsercache.html.w3tc' => false,
	'browsercache.html.compression' => true,
	'browsercache.other.last_modified' => true,
	'browsercache.other.expires' => true,
	'browsercache.other.lifetime' => 31536000,
	'browsercache.other.cache.control' => true,
	'browsercache.other.cache.policy' => 'cache_public_maxage',
	'browsercache.other.etag' => true,
	'browsercache.other.w3tc' => false,
	'browsercache.other.compression' => true,
	'browsercache.other.replace' => false,
	'browsercache.other.nocookies' => true,
	'browsercache.timestamp' => '1403123541',
	'notes.need_empty_objectcache' => false,
	'objectcache.debug' => false,
	'pgcache.reject.ua' => array(
		0 => 'MySiteApp',
	),
	'cdn.reject.ua' => array(
		0 => 'MySiteApp',
	),
	'pgcache.cache.home' => true,
	'pgcache.reject.front_page' => false,
	'pgcache.cache.feed' => true,
	'pgcache.cache.ssl' => false,
	'pgcache.cache.query' => true,
	'pgcache.cache.404' => false,
	'pgcache.check.domain' => false,
	'pgcache.reject.logged' => true,
	'pgcache.reject.logged_roles' => false,
	'pgcache.reject.roles' => array(
		0 => '',
	),
	'pgcache.prime.enabled' => true,
	'pgcache.prime.interval' => 900,
	'pgcache.prime.limit' => 10,
	'pgcache.prime.sitemap' => '/sitemap_index.xml',
	'pgcache.prime.post.enabled' => false,
	'pgcache.purge.front_page' => false,
	'pgcache.purge.home' => true,
	'pgcache.purge.post' => true,
	'pgcache.purge.feed.blog' => true,
	'pgcache.purge.comments' => false,
	'pgcache.purge.author' => false,
	'pgcache.purge.terms' => false,
	'pgcache.purge.feed.comments' => false,
	'pgcache.purge.feed.author' => false,
	'pgcache.purge.feed.terms' => false,
	'pgcache.purge.archive.daily' => false,
	'pgcache.purge.archive.monthly' => false,
	'pgcache.purge.archive.yearly' => false,
	'pgcache.purge.feed.types' => array(
		0 => 'rss2',
	),
	'pgcache.purge.postpages_limit' => 10,
	'pgcache.purge.pages' => array(
		0 => '',
	),
	'pgcache.purge.sitemap_regex' => '([a-z0-9_\\-]*?)sitemap([a-z0-9_\\-]*)?\\.xml',
	'pgcache.late_init' => true,
	'pgcache.file.gc' => 3600,
	'pgcache.comment_cookie_ttl' => 1800,
	'pgcache.accept.qs' => array(
		0 => '',
	),
	'pgcache.reject.cookie' => array(
		0 => 'wptouch_switch_toggle',
	),
	'pgcache.reject.uri' => array(
		0 => 'wp-.*\\.php',
		1 => 'index\\.php',
	),
	'pgcache.accept.files' => array(
		0 => 'wp-comments-popup.php',
		1 => 'wp-links-opml.php',
		2 => 'wp-locations.php',
	),
	'pgcache.accept.uri' => array(
		0 => 'sitemap(_index)?\\.xml(\\.gz)?',
		1 => '([a-z0-9_\\-]+)?sitemap\\.xsl',
		2 => '[a-z0-9_\\-]+-sitemap([0-9]+)?\\.xml(\\.gz)?',
	),
	'pgcache.cache.headers' => array(
		0 => 'Last-Modified',
		1 => 'Content-Type',
		2 => 'X-Pingback',
		3 => 'P3P',
	),
	'notes.cdn_upload' => true,
	'cdn.debug' => false,
	'extensions.active' => array(
		'cloudflare' => 'w3-total-cache/extensions/CloudFlare.php',
		'wordpress-seo' => 'w3-total-cache/extensions/WordPressSEO.php',
	),
	'extensions.settings' => array(
		'genesis.theme' => array(
			'wp_head' => '0',
			'genesis_header' => '1',
			'genesis_do_nav' => '0',
			'genesis_do_subnav' => '0',
			'loop_front_page' => '1',
			'loop_terms' => '1',
			'flush_terms' => '1',
			'loop_single' => '1',
			'loop_single_excluded' => '',
			'loop_single_genesis_comments' => '0',
			'loop_single_genesis_pings' => '0',
			'sidebar' => '0',
			'sidebar_excluded' => '',
			'genesis_footer' => '1',
			'wp_footer' => '0',
			'reject_logged_roles' => '1',
			'reject_logged_roles_on_actions' => array(
				0 => 'genesis_loop',
				1 => 'wp_head',
				2 => 'wp_footer',
			),
			'reject_roles' => array(
				0 => 'administrator',
			),
		),
		'feedburner' => array(
			'urls' => '',
		),
		'cloudflare' => array(
			'enabled' => '1',
			'email' => 'rajat1996@gmail.com',
			'key' => 'ce257c12a7a394d017d68a3d053b586f9b545',
			'zone' => 'http://cafemocha.org',
			'ips.ip4' => array(
				0 => '199.27.128.0/21',
				1 => '173.245.48.0/20',
				2 => '103.21.244.0/22',
				3 => '103.22.200.0/22',
				4 => '103.31.4.0/22',
				5 => '141.101.64.0/18',
				6 => '108.162.192.0/18',
				7 => '190.93.240.0/20',
				8 => '188.114.96.0/20',
				9 => '197.234.240.0/22',
				10 => '198.41.128.0/17',
				11 => '162.158.0.0/15',
				12 => '104.16.0.0/12',
			),
			'ips.ip6' => array(
				0 => '2400:cb00::/32',
				1 => '2606:4700::/32',
				2 => '2803:f800::/32',
				3 => '2405:b500::/32',
				4 => '2405:8100::/32',
			),
		),
	),
);